spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
minio:
  endpoint: http://10.35.11.23:9000
  accessKey: springboot
  secretKey: springboot123
  bucketName: springbootbucket
